"""empty message

Revision ID: 1e9e9ae744dc
Revises: 2cd208f9074b
Create Date: 2015-01-17 01:37:02.127176

"""

# revision identifiers, used by Alembic.
revision = '1e9e9ae744dc'
down_revision = '2cd208f9074b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
