"""empty message

Revision ID: 22c26d9c77a3
Revises: 1e9e9ae744dc
Create Date: 2015-01-17 01:44:09.998650

"""

# revision identifiers, used by Alembic.
revision = '22c26d9c77a3'
down_revision = '1e9e9ae744dc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
