"""empty message

Revision ID: 6a032244828
Revises: 10688d0d13c7
Create Date: 2015-01-18 04:58:21.006844

"""

# revision identifiers, used by Alembic.
revision = '6a032244828'
down_revision = '10688d0d13c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
